import { LevelConfig } from './types';

export const LEVELS: LevelConfig[] = [
  {
    name: 'SECTOR 7 OUTSKIRTS',
    duration: 45,
    spawnRate: 1800,
    enemyTypes: ['scout'],
    enemyHpMult: 1,
    enemySpeedMult: 1,
    bossHp: 30,
    bgColor: '#1a0a2e',
  },
  {
    name: 'ASTEROID BELT',
    duration: 50,
    spawnRate: 1400,
    enemyTypes: ['scout', 'mine'],
    enemyHpMult: 1.3,
    enemySpeedMult: 1.2,
    bossHp: 50,
    bgColor: '#0a1a2e',
  },
  {
    name: 'RINGS OF SATURN',
    duration: 55,
    spawnRate: 1100,
    enemyTypes: ['scout', 'mine'],
    enemyHpMult: 1.6,
    enemySpeedMult: 1.4,
    bossHp: 75,
    bgColor: '#1a0a1e',
  },
  {
    name: 'NEBULA CORE',
    duration: 60,
    spawnRate: 900,
    enemyTypes: ['scout', 'mine'],
    enemyHpMult: 2,
    enemySpeedMult: 1.6,
    bossHp: 100,
    bgColor: '#0e0a2e',
  },
  {
    name: 'ZOG MOTHERSHIP',
    duration: 70,
    spawnRate: 750,
    enemyTypes: ['scout', 'mine'],
    enemyHpMult: 2.5,
    enemySpeedMult: 1.8,
    bossHp: 150,
    bgColor: '#1e0a0a',
  },
];
